/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CaptainRouteImport } from './routes/captain'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as CreateTeamRouteImport } from './routes/create-team'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LiveMatchRouteImport } from './routes/live-match'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchDetailsRouteImport } from './routes/match-details'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as MyMatchesRouteImport } from './routes/my-matches'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as VerifyOtpLoginRouteImport } from './routes/verify-otp-login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainRoute = CaptainRouteImport.update({
  id: '/captain',
  path: '/captain',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTeamRoute = CreateTeamRouteImport.update({
  id: '/create-team',
  path: '/create-team',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMatchRoute = LiveMatchRouteImport.update({
  id: '/live-match',
  path: '/live-match',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchDetailsRoute = MatchDetailsRouteImport.update({
  id: '/match-details',
  path: '/match-details',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const MyMatchesRoute = MyMatchesRouteImport.update({
  id: '/my-matches',
  path: '/my-matches',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpLoginRoute = VerifyOtpLoginRouteImport.update({
  id: '/verify-otp-login',
  path: '/verify-otp-login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/captain': typeof CaptainRoute
  '/contests': typeof ContestsRoute
  '/create-team': typeof CreateTeamRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-match': typeof LiveMatchRoute
  '/login': typeof LoginRoute
  '/match-details': typeof MatchDetailsRoute
  '/matches': typeof MatchesRoute
  '/my-matches': typeof MyMatchesRoute
  '/players': typeof PlayersRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/verify-otp-login': typeof VerifyOtpLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/captain': typeof CaptainRoute
  '/contests': typeof ContestsRoute
  '/create-team': typeof CreateTeamRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-match': typeof LiveMatchRoute
  '/login': typeof LoginRoute
  '/match-details': typeof MatchDetailsRoute
  '/matches': typeof MatchesRoute
  '/my-matches': typeof MyMatchesRoute
  '/players': typeof PlayersRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/verify-otp-login': typeof VerifyOtpLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/captain': typeof CaptainRoute
  '/contests': typeof ContestsRoute
  '/create-team': typeof CreateTeamRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-match': typeof LiveMatchRoute
  '/login': typeof LoginRoute
  '/match-details': typeof MatchDetailsRoute
  '/matches': typeof MatchesRoute
  '/my-matches': typeof MyMatchesRoute
  '/players': typeof PlayersRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/verify-otp-login': typeof VerifyOtpLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/captain'
    | '/contests'
    | '/create-team'
    | '/leaderboard'
    | '/live-match'
    | '/login'
    | '/match-details'
    | '/matches'
    | '/my-matches'
    | '/players'
    | '/profile'
    | '/register'
    | '/results'
    | '/verify-otp'
    | '/verify-otp-login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/captain'
    | '/contests'
    | '/create-team'
    | '/leaderboard'
    | '/live-match'
    | '/login'
    | '/match-details'
    | '/matches'
    | '/my-matches'
    | '/players'
    | '/profile'
    | '/register'
    | '/results'
    | '/verify-otp'
    | '/verify-otp-login'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/captain'
    | '/contests'
    | '/create-team'
    | '/leaderboard'
    | '/live-match'
    | '/login'
    | '/match-details'
    | '/matches'
    | '/my-matches'
    | '/players'
    | '/profile'
    | '/register'
    | '/results'
    | '/verify-otp'
    | '/verify-otp-login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CaptainRoute: typeof CaptainRoute
  ContestsRoute: typeof ContestsRoute
  CreateTeamRoute: typeof CreateTeamRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LiveMatchRoute: typeof LiveMatchRoute
  LoginRoute: typeof LoginRoute
  MatchDetailsRoute: typeof MatchDetailsRoute
  MatchesRoute: typeof MatchesRoute
  MyMatchesRoute: typeof MyMatchesRoute
  PlayersRoute: typeof PlayersRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResultsRoute: typeof ResultsRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  VerifyOtpLoginRoute: typeof VerifyOtpLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain': {
      id: '/captain'
      path: '/captain'
      fullPath: '/captain'
      preLoaderRoute: typeof CaptainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-team': {
      id: '/create-team'
      path: '/create-team'
      fullPath: '/create-team'
      preLoaderRoute: typeof CreateTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-match': {
      id: '/live-match'
      path: '/live-match'
      fullPath: '/live-match'
      preLoaderRoute: typeof LiveMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-details': {
      id: '/match-details'
      path: '/match-details'
      fullPath: '/match-details'
      preLoaderRoute: typeof MatchDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-matches': {
      id: '/my-matches'
      path: '/my-matches'
      fullPath: '/my-matches'
      preLoaderRoute: typeof MyMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp-login': {
      id: '/verify-otp-login'
      path: '/verify-otp-login'
      fullPath: '/verify-otp-login'
      preLoaderRoute: typeof VerifyOtpLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CaptainRoute: CaptainRoute,
  ContestsRoute: ContestsRoute,
  CreateTeamRoute: CreateTeamRoute,
  LeaderboardRoute: LeaderboardRoute,
  LiveMatchRoute: LiveMatchRoute,
  LoginRoute: LoginRoute,
  MatchDetailsRoute: MatchDetailsRoute,
  MatchesRoute: MatchesRoute,
  MyMatchesRoute: MyMatchesRoute,
  PlayersRoute: PlayersRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResultsRoute: ResultsRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  VerifyOtpLoginRoute: VerifyOtpLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
