import { useEffect, useState } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import {
  Radio,
  ChevronRight,
  ChevronLeft,
  Play,
  Newspaper,
  Video,
  X,
  Sparkles,
  Flame,
  Clock,
  CheckCircle2,
} from "lucide-react";
import { AppShell } from "@/components/fc/AppShell";
import { Button } from "@/components/ui/button";
import { setFlow, FLOW_KEYS } from "@/lib/flow";
import { cn } from "@/lib/utils";
import heroCricket from "@/assets/hero-cricket.jpg";

export const Route = createFileRoute("/matches")({ component: Matches });

const TEAM_FLAGS: Record<string, string> = {
  INDIA: "🇮🇳",
  IND: "🇮🇳",
  AUSTRALIA: "🇦🇺",
  AUS: "🇦🇺",
  ENGLAND: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  ENG: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "SOUTH AFRICA": "🇿🇦",
  SA: "🇿🇦",
  "NEW ZEALAND": "🇳🇿",
  NZ: "🇳🇿",
  PAKISTAN: "🇵🇰",
  PAK: "🇵🇰",
  "PAKISTAN W": "🇵🇰",
  PAKW: "🇵🇰",
  "HONG KONG W": "🇭🇰",
  HKGW: "🇭🇰",
  BANGLADESH: "🇧🇩",
  BAN: "🇧🇩",
  "BANGLADESH WOMEN": "🇧🇩",
  "BANGLADESH W": "🇧🇩",
  BANW: "🇧🇩",
  "UNITED ARAB EMIRATES WOMEN": "🇦🇪",
  "UAE W": "🇦🇪",
  UAEW: "🇦🇪",
  "EAST ZONE": "🏏",
  EZONE: "🏏",
  "SOUTH ZONE": "🏏",
  SZONE: "🏏",
  "AMRITSAR LIONS (AMS)": "🦁",
  AMS: "🦁",
  "MOHALI KINGS (MHK)": "👑",
  MHK: "👑",
  "GUYANA AMAZON WARRIORS": "🏹",
  GAW: "🏹",
  "ANTIGUA AND BARBUDA FALCONS": "🦅",
  ABF: "🦅",
  YORKSHIRE: "🏏",
  YORKS: "🏏",
  ESSEX: "🏏",
  ESS: "🏏",
  CSK: "🦁",
  "CHENNAI SUPER KINGS": "🦁",
  MI: "⚡",
  "MUMBAI INDIANS": "⚡",
  RCB: "🔥",
  "ROYAL CHALLENGERS BANGALORE": "🔥",
  KKR: "⚔️",
  "KOLKATA KNIGHT RIDERS": "⚔️",
};

function getTeamFlag(name?: string): string {
  if (!name) return "🏏";
  const upper = name.toUpperCase().trim();
  return TEAM_FLAGS[upper] || "🏏";
}

interface NewsArticle {
  id: string;
  title: string;
  category: string;
  timeAgo: string;
  image?: string;
  author?: string;
  summary: string;
  content: string[];
}

interface VideoHighlight {
  id: string;
  title: string;
  duration: string;
  views: string;
  thumbnail: string;
  youtubeId: string;
  description: string;
}

const FEATURED_ARTICLES: NewsArticle[] = [
  {
    id: "art-1",
    title: "Cricket Australia officially opens door to private investment in Big Bash",
    category: "BIG BASH LEAGUE",
    timeAgo: "4h ago",
    author: "Peter Lalor • Cricbuzz Senior Editor",
    image: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1200&q=80",
    summary: "Cricket Australia will invite bids from private investors for the Melbourne Renegades, with the view to the club entering the 2027-28 season under new global ownership.",
    content: [
      "Cricket Australia has formally ratified a landmark decision to permit private equity and commercial venture syndicates to purchase equity stakes in Big Bash League franchises starting next year.",
      "The initial pilot initiative will focus on Melbourne Renegades, with prospective investors from India's IPL groups, North American sports funds, and regional conglomerates expressing formal interest in acquiring up to a 49% stake.",
      "'This represents an exciting evolution for Australian cricket,' said CA chief executive. 'Infusing private capital while preserving tournament integrity ensures the BBL remains a tier-one destination for top international cricket talent.'"
    ],
  },
  {
    id: "art-2",
    title: "Duleep Trophy 2026: East Zone dominate final with mammoth 708 first-innings total",
    category: "DOMESTIC CRICKET",
    timeAgo: "7h ago",
    author: "Somesh Sharma • Domestic Bureau",
    image: "https://images.unsplash.com/photo-1531415074868-036b1c57e329?auto=format&fit=crop&w=1200&q=80",
    summary: "East Zone piled on a monumental total of 708 against South Zone, backed by centuries from Kumar Kushagra and Shahbaz Ahmed on day three.",
    content: [
      "East Zone have positioned themselves within touching distance of the Duleep Trophy silverware following a commanding batting display in Chennai that yielded 708 runs.",
      "South Zone struggled in reply against the seam movement generated by Mohammed Shami and Mukesh Kumar, slumping to 217/5 before the evening session.",
      "Tilak Varma is batting unbeaten on 44 with Shreyas Gopal (15*) providing support, but South Zone remain 491 runs behind."
    ],
  },
  {
    id: "art-3",
    title: "Injuries hit India's squad! Jasprit Bumrah returns while Hardik Pandya rested",
    category: "TEAM INDIA",
    timeAgo: "10h ago",
    author: "Rakesh Rao • Mumbai",
    image: "https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?auto=format&fit=crop&w=1200&q=80",
    summary: "Selection committee confirms squad rotation ahead of the crucial white-ball tri-series with Bumrah regaining full bowling loads.",
    content: [
      "India's pace spearhead Jasprit Bumrah has officially completed his rehabilitation protocols at the National Cricket Academy and is slated to return to action this week.",
      "All-rounder Hardik Pandya has been granted a precautionary rest period following high workload demands across recent T20 encounters.",
      "The selectors have also handed maiden call-ups to two standout domestic performers following impressive showings in the Syed Mushtaq Ali Trophy."
    ],
  },
  {
    id: "art-4",
    title: "Afghanistan to host Zimbabwe, Bangladesh in marquee ODI tri-series",
    category: "INTERNATIONAL",
    timeAgo: "12h ago",
    author: "Cricbuzz Global Desk",
    image: "https://images.unsplash.com/photo-1512719994953-eabf50895df7?auto=format&fit=crop&w=1200&q=80",
    summary: "The ACB has finalized venues in the UAE for an action-packed 10-match ODI triangular series starting next month.",
    content: [
      "Afghanistan Cricket Board (ACB) announced a triangular ODI tournament featuring Bangladesh and Zimbabwe, scheduled to be held across Sharjah and Dubai.",
      "The tournament will serve as critical preparation for the upcoming ICC Champions Trophy, offering subcontinental conditions to test batting depths."
    ],
  },
  {
    id: "art-5",
    title: "IPL 2027 Mega Auction: Franchises strategize on Right to Match (RTM) options",
    category: "IPL NEWS",
    timeAgo: "14h ago",
    author: "K. Shriniwas • Bengaluru",
    image: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1200&q=80",
    summary: "Franchise owners submitted consensus proposals to the IPL Governing Council regarding player purse ceilings and retention caps.",
    content: [
      "With the mega auction scheduled for late 2026, discussions are underway regarding the potential reintroduction of Right to Match cards and revised purse limits.",
      "Leading franchise executives emphasized the importance of maintaining squad continuity while creating exciting bidding wars for uncapped Indian talent."
    ],
  },
];

const FEATURED_VIDEOS: VideoHighlight[] = [
  {
    id: "vid-1",
    title: "Injuries hit India's squad! Bumrah returns... Where's Hardik?",
    duration: "02:56",
    views: "184K views",
    thumbnail: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=600&q=80",
    youtubeId: "dQw4w9WgXcQ",
    description: "In-depth tactical analysis on India's pace bowling combinations with Bumrah returning and fitness reports on key all-rounders.",
  },
  {
    id: "vid-2",
    title: "Pakistan hit new low! 7 players sent home & new coach in",
    duration: "03:27",
    views: "312K views",
    thumbnail: "https://images.unsplash.com/photo-1531415074868-036b1c57e329?auto=format&fit=crop&w=600&q=80",
    youtubeId: "dQw4w9WgXcQ",
    description: "Comprehensive review of the PCB overhaul, selection changes, and tactical preview for their upcoming white-ball series.",
  },
  {
    id: "vid-3",
    title: "Impact Player Rule Debate: Stay or Go? Captains Speak Out",
    duration: "03:22",
    views: "95K views",
    thumbnail: "https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?auto=format&fit=crop&w=600&q=80",
    youtubeId: "dQw4w9WgXcQ",
    description: "Leading T20 franchise coaches and players weigh in on how the Impact Player innovation has reshaped 200+ totals.",
  },
  {
    id: "vid-4",
    title: "Top 10 Unbelievable Catches in Modern Cricket History",
    duration: "04:15",
    views: "520K views",
    thumbnail: "https://images.unsplash.com/photo-1512719994953-eabf50895df7?auto=format&fit=crop&w=600&q=80",
    youtubeId: "dQw4w9WgXcQ",
    description: "Relive the greatest boundary-line acrobatics, relay catches, and diving blinders from international cricket.",
  },
];

async function fetchWorldMatches() {
  try {
    const res = await fetch("/api/v1/cricket/live");
    const json = await res.json();
    return json.data || [];
  } catch {
    try {
      const res2 = await fetch("/api/cricket/live");
      const json2 = await res2.json();
      return json2.data || [];
    } catch {
      return [];
    }
  }
}

async function fetchCricketNews() {
  try {
    const res = await fetch("/api/v1/cricket/news");
    const json = await res.json();
    return json.data || [];
  } catch {
    try {
      const res2 = await fetch("/api/cricket/news");
      const json2 = await res2.json();
      return json2.data || [];
    } catch {
      return [];
    }
  }
}

function Matches() {
  const navigate = useNavigate();

  const [worldMatches, setWorldMatches] = useState<any[]>([]);
  const [news, setNews] = useState<any[]>([]);
  const [tickerPage, setTickerPage] = useState(0);

  // Modals
  const [activeArticle, setActiveArticle] = useState<NewsArticle | null>(null);
  const [activeVideo, setActiveVideo] = useState<VideoHighlight | null>(null);

  useEffect(() => {
    fetchWorldMatches().then((data) => {
      if (Array.isArray(data) && data.length > 0) {
        setWorldMatches(data);
      }
    });
    fetchCricketNews().then((data) => {
      if (Array.isArray(data) && data.length > 0) setNews(data);
    });
  }, []);

  const statusPriority: Record<string, number> = {
    LIVE: 1,
    COMPLETED: 2,
    UPCOMING: 3,
  };

  const sortedMatches = [...worldMatches].sort((a, b) => {
    const pA = statusPriority[a.status?.toUpperCase()] || 4;
    const pB = statusPriority[b.status?.toUpperCase()] || 4;
    return pA - pB;
  });

  const PAGE_SIZE = 3;
  const totalMatches = sortedMatches.length;
  const totalPages = Math.ceil(totalMatches / PAGE_SIZE) || 1;

  function handleNextTicker() {
    setTickerPage((prev) => (prev + 1) % totalPages);
  }

  function handlePrevTicker() {
    setTickerPage((prev) => (prev - 1 + totalPages) % totalPages);
  }

  const currentTickerMatches = sortedMatches.slice(
    tickerPage * PAGE_SIZE,
    tickerPage * PAGE_SIZE + PAGE_SIZE
  );

  function handleTickerMatchClick(wm: any) {
    const id = wm.id || wm.dbId;
    if (id) {
      setFlow(FLOW_KEYS.selectedMatchId, id);
      navigate({ to: "/live-match", search: { matchId: id } as any });
    }
  }

  const heroArticle = FEATURED_ARTICLES[0];
  const sideArticles = FEATURED_ARTICLES.slice(1, 4);

  return (
    <AppShell maxWidth="max-w-[1550px]">
      {/* ------------------------------------------------------------- */}
      {/* 1. CRICBUZZ-STYLE TOP LIVE MATCH TICKER STRIP WITH PAGINATION  */}
      {/* ------------------------------------------------------------- */}
      <div className="-mx-4 sm:-mx-6 -mt-6 mb-8 bg-gradient-to-r from-[#072d20] via-[#0b3d2b] to-[#072d20] text-white border-b border-emerald-900/60 shadow-lg select-none">
        <div className="flex items-center gap-2 px-3 py-2.5">
          {/* Matches Brand Badge */}
          <div className="flex items-center gap-1 text-xs font-black shrink-0 px-3 py-2 bg-black/50 rounded-md text-emerald-400 border border-emerald-500/30">
            <Radio className="h-3.5 w-3.5 text-red-400 animate-pulse" />
            <span>MATCHES</span>
          </div>

          {/* Left Arrow Button (Paginates to previous 3 matches) */}
          <button
            type="button"
            onClick={handlePrevTicker}
            title="Previous 3 matches"
            aria-label="Previous matches"
            className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-950/80 hover:bg-emerald-600/60 text-white/90 hover:text-white border border-emerald-500/30 transition-all cursor-pointer shadow"
          >
            <ChevronLeft className="h-5 w-5" />
          </button>

          {/* Ticker 3 Match Cards Grid */}
          <div className="flex-1 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">
            {currentTickerMatches.length > 0 ? (
              currentTickerMatches.map((wm, i) => (
                <div
                  key={wm.id || i}
                  onClick={() => handleTickerMatchClick(wm)}
                  className="bg-black/30 hover:bg-white/15 border border-emerald-500/20 hover:border-emerald-400/50 rounded-lg px-3.5 py-2.5 text-xs flex flex-col justify-between cursor-pointer transition-all duration-200 shadow-sm group"
                >
                  {/* Card Header: Series + Format */}
                  <div className="flex justify-between items-center text-[10px] text-emerald-300/80 font-bold uppercase tracking-wider pb-1 border-b border-white/5">
                    <span className="truncate max-w-[170px]">{wm.series || "World Series"}</span>
                    <span className="bg-emerald-500/20 text-emerald-300 px-1.5 py-0.5 rounded text-[9px] font-black">
                      {wm.format || "T20"}
                    </span>
                  </div>

                  {/* Team A vs Team B Scores */}
                  <div className="flex flex-col gap-1.5 my-2">
                    <div className="flex justify-between items-center font-bold">
                      <span className="flex items-center gap-1.5 truncate max-w-[170px]">
                        <span className="text-sm">{getTeamFlag(wm.teamA)}</span>
                        <span className="truncate group-hover:text-emerald-300 transition-colors">
                          {wm.teamACode || wm.teamA}
                        </span>
                      </span>
                      <span className="font-mono text-emerald-300 text-[12px] font-bold">
                        {wm.scoreA || ""}
                      </span>
                    </div>

                    <div className="flex justify-between items-center font-bold">
                      <span className="flex items-center gap-1.5 truncate max-w-[170px]">
                        <span className="text-sm">{getTeamFlag(wm.teamB)}</span>
                        <span className="truncate group-hover:text-emerald-300 transition-colors">
                          {wm.teamBCode || wm.teamB}
                        </span>
                      </span>
                      <span className="font-mono text-emerald-300 text-[12px] font-bold">
                        {wm.scoreB || ""}
                      </span>
                    </div>
                  </div>

                  {/* Card Footer: Status text & Live Pulse Indicator */}
                  <div className="flex justify-between items-center border-t border-white/10 pt-1.5 text-[10px]">
                    <span className="text-emerald-200/90 truncate max-w-[210px] font-medium">
                      {wm.statusText || wm.status || "Match Scheduled"}
                    </span>
                    {wm.status === "LIVE" ? (
                      <span className="flex items-center gap-1 text-[9px] text-red-400 font-black uppercase">
                        <span className="h-2 w-2 rounded-full bg-red-500 animate-pulse" />
                        LIVE
                      </span>
                    ) : wm.status === "COMPLETED" ? (
                      <span className="flex items-center gap-1 text-[9px] text-white/50 uppercase">
                        <CheckCircle2 className="h-2.5 w-2.5 text-emerald-400" />
                        FINAL
                      </span>
                    ) : (
                      <span className="flex items-center gap-1 text-[9px] text-amber-300 uppercase">
                        <Clock className="h-2.5 w-2.5" />
                        PREVIEW
                      </span>
                    )}
                  </div>
                </div>
              ))
            ) : (
              <div className="col-span-3 text-xs text-white/60 py-4 text-center">
                Loading worldwide cricket fixtures...
              </div>
            )}
          </div>

          {/* Right Arrow Button (Paginates to next 3 matches) */}
          <button
            type="button"
            onClick={handleNextTicker}
            title="Next 3 matches"
            aria-label="Next matches"
            className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-950/80 hover:bg-emerald-600/60 text-white/90 hover:text-white border border-emerald-500/30 transition-all cursor-pointer shadow"
          >
            <ChevronRight className="h-5 w-5" />
          </button>

          {/* ALL Button (Paginates to next 3 right inside ticker as requested) */}
          <button
            type="button"
            onClick={handleNextTicker}
            title="Cycle next matches"
            className="text-xs font-black shrink-0 px-3.5 py-2 rounded-md bg-emerald-500/25 hover:bg-emerald-500/40 text-emerald-300 border border-emerald-500/30 transition-colors flex items-center gap-1 cursor-pointer"
          >
            <span>ALL</span>
            <ChevronRight className="h-3.5 w-3.5" />
          </button>

          {/* Page Counter */}
          <span className="text-[10px] font-mono text-emerald-400/80 shrink-0 hidden md:inline">
            {tickerPage + 1}/{totalPages}
          </span>
        </div>
      </div>

      {/* ------------------------------------------------------------- */}
      {/* 2. THREE-COLUMN CRICBUZZ LAYOUT (NO FIXTURES DOWN BELOW!)     */}
      {/* ------------------------------------------------------------- */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* ========================================================= */}
        {/* LEFT COLUMN (LATEST NEWS) - 3 cols                         */}
        {/* ========================================================= */}
        <div className="lg:col-span-3 space-y-4">
          <div className="flex items-center justify-between border-b border-border/80 pb-2">
            <h3 className="text-red-500 font-display text-xs font-black uppercase tracking-wider flex items-center gap-1.5">
              <Newspaper className="h-4 w-4 text-red-500" />
              <span>LATEST NEWS</span>
            </h3>
            <span className="text-[10px] text-muted-foreground font-bold uppercase">UPDATED</span>
          </div>

          <div className="flex flex-col divide-y divide-border/60 bg-surface/70 border border-border/70 rounded-2xl p-2 shadow-sm">
            {(news.length > 0 ? news : FEATURED_ARTICLES).slice(0, 8).map((n: any, i: number) => {
              const articleObj: NewsArticle = {
                id: n.id || `news-${i}`,
                title: n.title,
                category: n.category || "Cricket News",
                timeAgo: n.timeAgo || `${i + 1}h ago`,
                author: n.author || "Cricbuzz Staff",
                image: n.image || FEATURED_ARTICLES[i % FEATURED_ARTICLES.length].image,
                summary: n.summary || n.title,
                content: n.content || [
                  n.title,
                  "Officials and team representatives have met to formalize the tournament protocols. Further strategic updates will be shared ahead of upcoming matchdays.",
                  "Fans and fantasy managers can follow live ball-by-ball updates directly inside the Fantasy Cricket Arena."
                ],
              };

              return (
                <div
                  key={i}
                  onClick={() => setActiveArticle(articleObj)}
                  className="p-3 group cursor-pointer hover:bg-surface-2/80 rounded-xl transition-colors"
                >
                  <div className="flex items-center justify-between text-[10px] text-primary font-bold uppercase tracking-wider mb-1">
                    <span>{articleObj.category}</span>
                    <span className="text-muted-foreground font-normal">{articleObj.timeAgo}</span>
                  </div>
                  <h4 className="text-xs font-bold text-foreground group-hover:text-primary transition-colors leading-relaxed">
                    {articleObj.title}
                  </h4>
                </div>
              );
            })}
          </div>
        </div>

        {/* ========================================================= */}
        {/* CENTER COLUMN (HERO ARTICLE + EDITORIAL STORIES) - 6 cols  */}
        {/* ========================================================= */}
        <div className="lg:col-span-6 space-y-6 min-w-0">
          {/* Featured Hero Article Banner */}
          <div
            onClick={() => setActiveArticle(heroArticle)}
            className="group relative overflow-hidden rounded-2xl border border-border/80 bg-surface/90 shadow-lg hover:border-primary/60 cursor-pointer transition-all duration-300"
          >
            {/* Top Category Tag */}
            <div className="px-5 pt-3 pb-2 text-[10px] font-black uppercase tracking-wider text-muted-foreground flex items-center justify-between border-b border-border/40 bg-surface-2/40">
              <span className="text-emerald-400 font-bold">{heroArticle.category}</span>
              <span>{heroArticle.timeAgo}</span>
            </div>

            {/* Wide 16:9 Image Container */}
            <div className="relative h-48 sm:h-64 w-full overflow-hidden bg-surface-2">
              <img
                src={heroArticle.image || heroCricket}
                alt={heroArticle.title}
                className="h-full w-full object-cover object-center group-hover:scale-105 transition-transform duration-500"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/30 to-transparent" />
              <div className="absolute top-3 left-3 bg-red-600 text-white text-[10px] font-black px-2.5 py-0.5 rounded-full shadow-md flex items-center gap-1">
                <Sparkles className="h-3 w-3" /> FEATURED STORY
              </div>
            </div>

            {/* Story Content Below Image */}
            <div className="p-5">
              <h2 className="font-display text-lg sm:text-xl font-black text-foreground group-hover:text-primary transition-colors leading-snug">
                {heroArticle.title}
              </h2>
              <p className="mt-2 text-xs text-muted-foreground leading-relaxed line-clamp-2">
                {heroArticle.summary}
              </p>
              <div className="mt-3 flex items-center justify-between text-[11px] font-semibold text-primary pt-2 border-t border-border/40">
                <span>Read Full Story &rarr;</span>
                <span className="text-muted-foreground">{heroArticle.author}</span>
              </div>
            </div>
          </div>

          {/* Additional Editorial Feature Stories (Cricbuzz Home Grid) */}
          <div className="space-y-4">
            <div className="flex items-center gap-2 border-b border-border/80 pb-2">
              <Flame className="h-4 w-4 text-amber-500" />
              <h3 className="font-display text-xs font-black uppercase tracking-wider text-foreground">
                SPECIAL FEATURES & ANALYSIS
              </h3>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {sideArticles.map((art) => (
                <div
                  key={art.id}
                  onClick={() => setActiveArticle(art)}
                  className="group rounded-2xl border border-border/70 bg-surface/80 hover:border-primary/50 overflow-hidden cursor-pointer transition-all shadow-sm flex flex-col justify-between"
                >
                  <div className="relative h-36 w-full overflow-hidden bg-surface-2">
                    <img
                      src={art.image}
                      alt={art.title}
                      className="h-full w-full object-cover group-hover:scale-105 transition-transform duration-300"
                    />
                    <div className="absolute top-2 left-2 bg-black/70 text-white text-[9px] font-black px-2 py-0.5 rounded">
                      {art.category}
                    </div>
                  </div>
                  <div className="p-4 flex-1 flex flex-col justify-between">
                    <div>
                      <h4 className="text-xs font-bold text-foreground group-hover:text-primary transition-colors leading-snug line-clamp-2">
                        {art.title}
                      </h4>
                      <p className="mt-1.5 text-[11px] text-muted-foreground line-clamp-2 leading-relaxed">
                        {art.summary}
                      </p>
                    </div>
                    <div className="mt-3 pt-2 border-t border-border/40 flex items-center justify-between text-[10px] text-muted-foreground">
                      <span>{art.author?.split("•")[0]}</span>
                      <span>{art.timeAgo}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* ========================================================= */}
        {/* RIGHT COLUMN (FEATURED VIDEOS) - 3 cols                    */}
        {/* ========================================================= */}
        <div className="lg:col-span-3 space-y-4">
          <div className="flex items-center justify-between border-b border-border/80 pb-2">
            <h3 className="text-red-500 font-display text-xs font-black uppercase tracking-wider flex items-center gap-1.5">
              <Video className="h-4 w-4 text-red-500" />
              <span>FEATURED VIDEOS</span>
            </h3>
            <span className="text-[10px] text-muted-foreground font-bold uppercase">HIGHLIGHTS</span>
          </div>

          <div className="space-y-4">
            {FEATURED_VIDEOS.map((v) => (
              <div
                key={v.id}
                onClick={() => setActiveVideo(v)}
                className="group cursor-pointer rounded-2xl overflow-hidden border border-border/70 bg-surface/70 hover:border-primary/60 transition-all p-2.5 shadow-sm"
              >
                <div className="relative h-36 rounded-xl overflow-hidden bg-surface-2 flex items-center justify-center mb-2.5">
                  <img
                    src={v.thumbnail}
                    alt={v.title}
                    className="h-full w-full object-cover group-hover:scale-105 transition-transform duration-300"
                  />
                  <div className="absolute inset-0 bg-black/40 group-hover:bg-black/20 transition-colors" />
                  <div className="bg-primary/90 text-primary-foreground rounded-full p-2.5 z-10 shadow-lg group-hover:scale-110 transition-transform">
                    <Play className="h-4 w-4 fill-current" />
                  </div>
                  <span className="absolute bottom-2 right-2 bg-black/80 text-white text-[10px] font-black px-1.5 py-0.5 rounded">
                    {v.duration}
                  </span>
                </div>
                <h4 className="text-xs font-bold text-foreground group-hover:text-primary transition-colors leading-snug line-clamp-2">
                  {v.title}
                </h4>
                <p className="text-[10px] text-muted-foreground mt-1">{v.views}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* ------------------------------------------------------------- */}
      {/* ARTICLE READING MODAL (Opens when clicking any news/story)     */}
      {/* ------------------------------------------------------------- */}
      {activeArticle && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in">
          <div className="relative w-full max-w-2xl max-h-[85vh] overflow-y-auto rounded-2xl border border-border bg-surface p-6 shadow-2xl space-y-4">
            <div className="flex items-center justify-between border-b border-border/60 pb-3">
              <span className="text-xs font-black uppercase text-primary tracking-wider">
                {activeArticle.category}
              </span>
              <button
                type="button"
                onClick={() => setActiveArticle(null)}
                aria-label="Close article modal"
                className="h-8 w-8 rounded-full bg-surface-2 hover:bg-surface text-muted-foreground hover:text-foreground flex items-center justify-center transition-colors"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <h2 className="font-display text-xl sm:text-2xl font-black text-foreground leading-tight">
              {activeArticle.title}
            </h2>

            <div className="flex items-center justify-between text-xs text-muted-foreground border-b border-border/40 pb-2">
              <span>{activeArticle.author || "Cricbuzz Staff"}</span>
              <span>{activeArticle.timeAgo}</span>
            </div>

            {activeArticle.image && (
              <div className="h-52 w-full overflow-hidden rounded-xl bg-surface-2">
                <img
                  src={activeArticle.image}
                  alt={activeArticle.title}
                  className="h-full w-full object-cover"
                />
              </div>
            )}

            <div className="space-y-3 text-sm text-foreground/90 leading-relaxed">
              {activeArticle.content.map((p, idx) => (
                <p key={idx}>{p}</p>
              ))}
            </div>

            <div className="pt-4 border-t border-border flex items-center justify-between">
              <span className="text-xs text-muted-foreground">Fantasy Cricket Arena &bull; Global Feed</span>
              <Button
                type="button"
                variant="hero"
                size="sm"
                onClick={() => setActiveArticle(null)}
              >
                Close Story
              </Button>
            </div>
          </div>
        </div>
      )}

      {/* ------------------------------------------------------------- */}
      {/* VIDEO PLAYER MODAL (Opens when clicking any video)            */}
      {/* ------------------------------------------------------------- */}
      {activeVideo && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-sm animate-in fade-in">
          <div className="relative w-full max-w-3xl rounded-2xl border border-border bg-surface p-6 shadow-2xl space-y-4">
            <div className="flex items-center justify-between border-b border-border/60 pb-3">
              <span className="text-xs font-black uppercase text-red-400 tracking-wider flex items-center gap-1.5">
                <Video className="h-4 w-4" /> CRICKET HIGHLIGHTS &bull; {activeVideo.duration}
              </span>
              <button
                type="button"
                onClick={() => setActiveVideo(null)}
                aria-label="Close video modal"
                className="h-8 w-8 rounded-full bg-surface-2 hover:bg-surface text-muted-foreground hover:text-foreground flex items-center justify-center transition-colors"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <div className="relative aspect-video w-full overflow-hidden rounded-xl bg-black flex items-center justify-center shadow-inner">
              <iframe
                title={activeVideo.title}
                className="w-full h-full"
                src={`https://www.youtube-nocookie.com/embed/${activeVideo.youtubeId}?autoplay=1&mute=0`}
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              />
            </div>

            <div>
              <h3 className="font-display text-lg font-bold text-foreground">{activeVideo.title}</h3>
              <p className="mt-1 text-xs text-muted-foreground leading-relaxed">{activeVideo.description}</p>
            </div>

            <div className="pt-3 border-t border-border flex items-center justify-between">
              <span className="text-xs text-muted-foreground">{activeVideo.views}</span>
              <Button
                type="button"
                variant="outlineGreen"
                size="sm"
                onClick={() => setActiveVideo(null)}
              >
                Close Player
              </Button>
            </div>
          </div>
        </div>
      )}
    </AppShell>
  );
}
