import { useEffect, useState, useRef } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import {
  Clock,
  RefreshCw,
  Trophy,
  MapPin,
  Radio,
  Globe2,
  CalendarDays,
  ChevronRight,
  ChevronLeft,
  Play,
  Newspaper,
  Video,
  X,
  Sparkles,
} from "lucide-react";
import { AppShell } from "@/components/fc/AppShell";
import { Card, StatusBadge } from "@/components/fc/bits";
import { LoadingState, EmptyState, LoadMoreButton } from "@/components/fc/ListState";
import { Button } from "@/components/ui/button";
import { getMatches } from "@/lib/api-services";
import type { Match } from "@/lib/api-types";
import { setFlow, FLOW_KEYS } from "@/lib/flow";
import { ApiClientError } from "@/lib/api";
import { useLoadMore } from "@/hooks/use-load-more";
import { getSocket } from "@/lib/socket";
import { cn } from "@/lib/utils";
import heroCricket from "@/assets/hero-cricket.jpg";

export const Route = createFileRoute("/matches")({ component: Matches });

const TEAM_FLAGS: Record<string, string> = {
  INDIA: "🇮🇳",
  IND: "🇮🇳",
  AUSTRALIA: "🇦🇺",
  AUS: "🇦🇺",
  ENGLAND: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  ENG: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "SOUTH AFRICA": "🇿🇦",
  SA: "🇿🇦",
  "NEW ZEALAND": "🇳🇿",
  NZ: "🇳🇿",
  PAKISTAN: "🇵🇰",
  PAK: "🇵🇰",
  "PAKISTAN W": "🇵🇰",
  PAKW: "🇵🇰",
  "HONG KONG W": "🇭🇰",
  HKGW: "🇭🇰",
  BANGLADESH: "🇧🇩",
  BAN: "🇧🇩",
  "BANGLADESH W": "🇧🇩",
  BANW: "🇧🇩",
  "UAE W": "🇦🇪",
  UAEW: "🇦🇪",
  "EAST ZONE": "🏏",
  EZONE: "🏏",
  "SOUTH ZONE": "🏏",
  SZONE: "🏏",
  CSK: "🦁",
  "CHENNAI SUPER KINGS": "🦁",
  MI: "⚡",
  "MUMBAI INDIANS": "⚡",
  RCB: "🔥",
  "ROYAL CHALLENGERS BANGALORE": "🔥",
  KKR: "⚔️",
  "KOLKATA KNIGHT RIDERS": "⚔️",
};

function getTeamFlag(name?: string): string {
  if (!name) return "🏏";
  const upper = name.toUpperCase().trim();
  return TEAM_FLAGS[upper] || "🏏";
}

interface NewsArticle {
  id: string;
  title: string;
  category: string;
  timeAgo: string;
  image?: string;
  author?: string;
  summary: string;
  content: string[];
}

interface VideoHighlight {
  id: string;
  title: string;
  duration: string;
  views: string;
  thumbnail: string;
  youtubeId: string;
  description: string;
}

const FEATURED_ARTICLES: NewsArticle[] = [
  {
    id: "art-1",
    title: "Cricket Australia officially opens door to private investment in Big Bash",
    category: "BIG BASH LEAGUE",
    timeAgo: "4h ago",
    author: "Peter Lalor • Cricbuzz Senior Editor",
    image: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1200&q=80",
    summary: "Cricket Australia will invite bids from private investors for the Melbourne Renegades, with the view to the club entering the 2027-28 season under new global ownership.",
    content: [
      "Cricket Australia has formally ratified a landmark decision to permit private equity and commercial venture syndicates to purchase equity stakes in Big Bash League franchises starting next year.",
      "The initial pilot initiative will focus on Melbourne Renegades, with prospective investors from India's IPL groups, North American sports funds, and regional conglomerates expressing formal interest in acquiring up to a 49% stake.",
      "'This represents an exciting evolution for Australian cricket,' said CA chief executive. 'Infusing private capital while preserving tournament integrity ensures the BBL remains a tier-one destination for top international cricket talent.'"
    ],
  },
  {
    id: "art-2",
    title: "Duleep Trophy 2026: East Zone dominate final with mammoth 708 first-innings lead",
    category: "DOMESTIC CRICKET",
    timeAgo: "7h ago",
    author: "Somesh Sharma • Domestic Bureau",
    image: "https://images.unsplash.com/photo-1531415074868-036b1c57e329?auto=format&fit=crop&w=1200&q=80",
    summary: "East Zone piled on a monumental total of 708 against South Zone, backed by centuries from Kumar Kushagra and Shahbaz Ahmed on day three.",
    content: [
      "East Zone have positioned themselves within touching distance of the Duleep Trophy silverware following a commanding batting display in Chennai that yielded 708 runs.",
      "South Zone struggled in reply against the seam movement generated by Mohammed Shami and Mukesh Kumar, slumping to 176/5 before the tea interval.",
      "Veteran pacer Mohammed Shami proved the standout bowler with two critical scalps in his opening spell, demonstrating full fitness ahead of India's upcoming international assignments."
    ],
  },
  {
    id: "art-3",
    title: "Injuries hit India's squad! Jasprit Bumrah returns while Hardik Pandya rested",
    category: "TEAM INDIA",
    timeAgo: "10h ago",
    author: "Rakesh Rao • Mumbai",
    image: "https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?auto=format&fit=crop&w=1200&q=80",
    summary: "Selection committee confirms squad rotation ahead of the crucial white-ball tri-series with Bumrah regaining full bowling loads.",
    content: [
      "India's pace spearhead Jasprit Bumrah has officially completed his rehabilitation protocols at the National Cricket Academy and is slated to return to action this week.",
      "All-rounder Hardik Pandya has been granted a precautionary rest period following high workload demands across recent T20 encounters.",
      "The selectors have also handed maiden call-ups to two standout domestic performers following impressive showings in the Syed Mushtaq Ali Trophy."
    ],
  },
  {
    id: "art-4",
    title: "Afghanistan to host Zimbabwe, Bangladesh in marquee ODI tri-series",
    category: "INTERNATIONAL",
    timeAgo: "12h ago",
    author: "Cricbuzz Global Desk",
    image: "https://images.unsplash.com/photo-1512719994953-eabf50895df7?auto=format&fit=crop&w=1200&q=80",
    summary: "The ACB has finalized venues in the UAE for an action-packed 10-match ODI triangular series starting next month.",
    content: [
      "Afghanistan Cricket Board (ACB) announced a triangular ODI tournament featuring Bangladesh and Zimbabwe, scheduled to be held across Sharjah and Dubai.",
      "The tournament will serve as critical preparation for the upcoming ICC Champions Trophy, offering subcontinental conditions to test batting depths."
    ],
  },
  {
    id: "art-5",
    title: "IPL 2027 Mega Auction: Franchises strategize on Right to Match (RTM) options",
    category: "IPL NEWS",
    timeAgo: "14h ago",
    author: "K. Shriniwas • Bengaluru",
    image: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1200&q=80",
    summary: "Franchise owners submitted consensus proposals to the IPL Governing Council regarding player purse ceilings and retention caps.",
    content: [
      "With the mega auction scheduled for late 2026, discussions are underway regarding the potential reintroduction of Right to Match cards and revised purse limits.",
      "Leading franchise executives emphasized the importance of maintaining squad continuity while creating exciting bidding wars for uncapped Indian talent."
    ],
  },
];

const FEATURED_VIDEOS: VideoHighlight[] = [
  {
    id: "vid-1",
    title: "Injuries hit India's squad! Bumrah returns... Where's Hardik?",
    duration: "02:56",
    views: "184K views",
    thumbnail: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=600&q=80",
    youtubeId: "dQw4w9WgXcQ",
    description: "In-depth tactical analysis on India's pace bowling combinations with Bumrah returning and fitness reports on key all-rounders.",
  },
  {
    id: "vid-2",
    title: "Pakistan hit new low! 7 players sent home & new coach in",
    duration: "03:27",
    views: "312K views",
    thumbnail: "https://images.unsplash.com/photo-1531415074868-036b1c57e329?auto=format&fit=crop&w=600&q=80",
    youtubeId: "dQw4w9WgXcQ",
    description: "Comprehensive review of the PCB overhaul, selection changes, and tactical preview for their upcoming white-ball series.",
  },
  {
    id: "vid-3",
    title: "Impact Player Rule Debate: Stay or Go? Captains Speak Out",
    duration: "03:22",
    views: "95K views",
    thumbnail: "https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?auto=format&fit=crop&w=600&q=80",
    youtubeId: "dQw4w9WgXcQ",
    description: "Leading T20 franchise coaches and players weigh in on how the Impact Player innovation has reshaped 200+ totals.",
  },
  {
    id: "vid-4",
    title: "Top 10 Unbelievable Catches in Modern Cricket History",
    duration: "04:15",
    views: "520K views",
    thumbnail: "https://images.unsplash.com/photo-1512719994953-eabf50895df7?auto=format&fit=crop&w=600&q=80",
    youtubeId: "dQw4w9WgXcQ",
    description: "Relive the greatest boundary-line acrobatics, relay catches, and diving blinders from international cricket.",
  },
];

async function fetchWorldMatches() {
  try {
    const res = await fetch("/api/cricket/live");
    const json = await res.json();
    return json.data || [];
  } catch {
    return [];
  }
}

async function fetchCricketNews() {
  try {
    const res = await fetch("/api/cricket/news");
    const json = await res.json();
    return json.data || [];
  } catch {
    return [];
  }
}

function Matches() {
  const navigate = useNavigate();
  const tickerRef = useRef<HTMLDivElement>(null);
  const fixturesSectionRef = useRef<HTMLDivElement>(null);

  const [tab, setTab] = useState<"Live" | "Upcoming" | "Completed">("Live");
  const [category, setCategory] = useState<"ALL" | "INTERNATIONAL" | "DOMESTIC">("ALL");
  const [items, setItems] = useState<Match[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const [worldMatches, setWorldMatches] = useState<any[]>([]);
  const [news, setNews] = useState<any[]>([]);

  // Modals
  const [activeArticle, setActiveArticle] = useState<NewsArticle | null>(null);
  const [activeVideo, setActiveVideo] = useState<VideoHighlight | null>(null);

  useEffect(() => {
    fetchWorldMatches().then((data) => {
      if (Array.isArray(data) && data.length > 0) setWorldMatches(data);
    });
    fetchCricketNews().then((data) => {
      if (Array.isArray(data) && data.length > 0) setNews(data);
    });
  }, []);

  const filteredItems = items.filter((m) => {
    const targetStatus = tab === "Live" ? "LIVE" : tab === "Completed" ? "COMPLETED" : "UPCOMING";
    if (m.status !== targetStatus) return false;
    if (category === "ALL") return true;
    const cat = ((m.providerData as any)?.category || "INTERNATIONAL").toUpperCase();
    return cat === category;
  });

  const { visibleItems, hasMore, loadMore, reset } = useLoadMore(filteredItems, 6);

  async function load() {
    setLoading(true);
    setError("");
    try {
      const data = await getMatches(
        tab === "Live" ? "LIVE" : tab === "Completed" ? "COMPLETED" : "UPCOMING"
      );
      setItems(data);
      reset();
    } catch (err) {
      setError(
        err instanceof ApiClientError
          ? err.message
          : "Unable to load matches. Please check backend connection."
      );
      setItems([]);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void load();
  }, [tab]);

  // Real-time Socket.IO sync for ball-by-ball match updates
  useEffect(() => {
    const socket = getSocket();
    socket.emit("match:subscribe", "live-feed");

    const onScoreUpdate = (data: any) => {
      if (!data?.matchId) return;
      setItems((prev) =>
        prev.map((m) => {
          if (m._id === data.matchId) {
            return {
              ...m,
              status: data.status || m.status,
              providerData: {
                ...(m.providerData || {}),
                ...(data.providerData || {}),
              },
            };
          }
          return m;
        })
      );
    };

    socket.on("match:score_update", onScoreUpdate);
    return () => {
      socket.off("match:score_update", onScoreUpdate);
      socket.emit("match:unsubscribe", "live-feed");
    };
  }, []);

  function select(id: string) {
    setFlow(FLOW_KEYS.selectedMatchId, id);
  }

  function handleTickerMatchClick(wm: any) {
    const found = items.find((m) => m.providerMatchId === wm.id || m.teamA === wm.teamA);
    if (found) {
      setFlow(FLOW_KEYS.selectedMatchId, found._id);
    } else if (items.length > 0) {
      setFlow(FLOW_KEYS.selectedMatchId, items[0]._id);
    }
    navigate({ to: "/live-match" });
  }

  function scrollTicker(direction: "left" | "right") {
    if (tickerRef.current) {
      const amount = direction === "left" ? -300 : 300;
      tickerRef.current.scrollBy({ left: amount, behavior: "smooth" });
    }
  }

  function scrollToFixtures(chosenCategory?: "ALL" | "INTERNATIONAL" | "DOMESTIC") {
    if (chosenCategory) setCategory(chosenCategory);
    fixturesSectionRef.current?.scrollIntoView({ behavior: "smooth" });
  }

  const heroArticle = FEATURED_ARTICLES[0];

  return (
    <AppShell maxWidth="max-w-[1550px]">
      {/* ------------------------------------------------------------- */}
      {/* 1. CRICBUZZ-STYLE LIVE MATCH TICKER STRIP                      */}
      {/* ------------------------------------------------------------- */}
      <div className="-mx-4 sm:-mx-6 -mt-6 mb-6 bg-gradient-to-r from-[#072d20] via-[#0b3d2b] to-[#072d20] text-white border-b border-emerald-900/60 shadow-lg">
        <div className="flex items-center gap-2 px-3 py-2">
          {/* Matches Brand Badge */}
          <button
            type="button"
            onClick={() => scrollToFixtures("ALL")}
            className="flex items-center gap-1 text-xs font-black shrink-0 px-2.5 py-1.5 bg-black/40 rounded-md text-emerald-400 border border-emerald-500/30 hover:bg-black/60 transition-colors"
          >
            <Radio className="h-3 w-3 text-red-400 animate-pulse" />
            <span>MATCHES</span>
          </button>

          {/* Left Arrow Scroll */}
          <button
            type="button"
            onClick={() => scrollTicker("left")}
            aria-label="Scroll matches left"
            className="hidden sm:flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-black/30 hover:bg-primary/20 text-white/80 hover:text-white transition-colors"
          >
            <ChevronLeft className="h-4 w-4" />
          </button>

          {/* Ticker Cards Container */}
          <div
            ref={tickerRef}
            className="flex-1 flex overflow-x-auto scrollbar-none gap-3 items-center py-1 scroll-smooth"
          >
            {worldMatches.length > 0 ? (
              worldMatches.map((wm, i) => (
                <div
                  key={i}
                  onClick={() => handleTickerMatchClick(wm)}
                  className="shrink-0 min-w-[270px] max-w-[290px] bg-white/10 hover:bg-white/20 border border-white/10 rounded-lg px-3 py-2 text-xs flex flex-col gap-1 cursor-pointer transition-all duration-200 shadow-sm"
                >
                  <div className="flex justify-between items-center text-[10px] text-white/70 font-semibold uppercase">
                    <span className="truncate max-w-[170px]">{wm.series || "World Series"}</span>
                    <span className="bg-white/15 px-1.5 py-0.2 rounded text-[9px] font-black">{wm.format || "T20"}</span>
                  </div>

                  <div className="flex flex-col gap-1 my-1">
                    <div className="flex justify-between items-center font-bold">
                      <span className="flex items-center gap-1.5 truncate max-w-[170px]">
                        <span className="text-sm">{getTeamFlag(wm.teamA)}</span>
                        <span className="truncate">{wm.teamACode || wm.teamA}</span>
                      </span>
                      <span className="font-mono text-emerald-300 text-[11px]">{wm.scoreA || ""}</span>
                    </div>

                    <div className="flex justify-between items-center font-bold">
                      <span className="flex items-center gap-1.5 truncate max-w-[170px]">
                        <span className="text-sm">{getTeamFlag(wm.teamB)}</span>
                        <span className="truncate">{wm.teamBCode || wm.teamB}</span>
                      </span>
                      <span className="font-mono text-emerald-300 text-[11px]">{wm.scoreB || ""}</span>
                    </div>
                  </div>

                  <div className="flex justify-between items-center border-t border-white/10 pt-1">
                    <span className="text-[10px] text-emerald-300 truncate max-w-[210px] font-medium">
                      {wm.statusText || wm.status || "Match Scheduled"}
                    </span>
                    {wm.status === "LIVE" ? (
                      <span className="flex h-2 w-2 rounded-full bg-red-500 animate-pulse shrink-0" />
                    ) : (
                      <span className="text-[9px] text-white/60 uppercase">Info</span>
                    )}
                  </div>
                </div>
              ))
            ) : (
              <div className="text-xs text-white/60 px-4 py-2">Loading worldwide cricket fixtures...</div>
            )}
          </div>

          {/* Right Arrow Scroll */}
          <button
            type="button"
            onClick={() => scrollTicker("right")}
            aria-label="Scroll matches right"
            className="hidden sm:flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-black/30 hover:bg-primary/20 text-white/80 hover:text-white transition-colors"
          >
            <ChevronRight className="h-4 w-4" />
          </button>

          {/* All Link Button */}
          <button
            type="button"
            onClick={() => scrollToFixtures("ALL")}
            className="text-xs font-black shrink-0 px-3 py-1.5 rounded-md bg-emerald-500/20 hover:bg-emerald-500/30 text-emerald-300 transition-colors flex items-center gap-1"
          >
            <span>ALL</span>
            <ChevronRight className="h-3 w-3" />
          </button>
        </div>
      </div>

      {/* ------------------------------------------------------------- */}
      {/* 2. THREE-COLUMN CRICBUZZ LAYOUT                               */}
      {/* ------------------------------------------------------------- */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* ========================================================= */}
        {/* LEFT COLUMN (LATEST NEWS) - 3 cols                         */}
        {/* ========================================================= */}
        <div className="lg:col-span-3 space-y-4">
          <div className="flex items-center justify-between border-b border-border/80 pb-2">
            <h3 className="text-red-500 font-display text-xs font-black uppercase tracking-wider flex items-center gap-1.5">
              <Newspaper className="h-4 w-4 text-red-500" />
              <span>LATEST NEWS</span>
            </h3>
            <span className="text-[10px] text-muted-foreground font-bold uppercase">UPDATED</span>
          </div>

          <div className="flex flex-col divide-y divide-border/60 bg-surface/70 border border-border/70 rounded-2xl p-2 shadow-sm">
            {(news.length > 0 ? news : FEATURED_ARTICLES).slice(0, 8).map((n: any, i: number) => {
              const articleObj: NewsArticle = {
                id: n.id || `news-${i}`,
                title: n.title,
                category: n.category || "Cricket News",
                timeAgo: n.timeAgo || `${i + 1}h ago`,
                author: n.author || "Cricbuzz Staff",
                image: n.image || FEATURED_ARTICLES[i % FEATURED_ARTICLES.length].image,
                summary: n.summary || n.title,
                content: n.content || [
                  n.title,
                  "Officials and team representatives have met to formalize the tournament protocols. Further strategic updates will be shared ahead of upcoming matchdays.",
                  "Fans and fantasy managers can follow live ball-by-ball updates directly inside the Fantasy Cricket Arena."
                ],
              };

              return (
                <div
                  key={i}
                  onClick={() => setActiveArticle(articleObj)}
                  className="p-3 group cursor-pointer hover:bg-surface-2/80 rounded-xl transition-colors"
                >
                  <div className="flex items-center justify-between text-[10px] text-primary font-bold uppercase tracking-wider mb-1">
                    <span>{articleObj.category}</span>
                    <span className="text-muted-foreground font-normal">{articleObj.timeAgo}</span>
                  </div>
                  <h4 className="text-xs font-bold text-foreground group-hover:text-primary transition-colors leading-relaxed">
                    {articleObj.title}
                  </h4>
                </div>
              );
            })}
          </div>
        </div>

        {/* ========================================================= */}
        {/* CENTER COLUMN (MAIN HERO + MATCHES) - 6 cols               */}
        {/* ========================================================= */}
        <div className="lg:col-span-6 space-y-6 min-w-0">
          {/* Cricbuzz-Style Wide Hero Article Banner (FIXES 3RD IMAGE!) */}
          <div
            onClick={() => setActiveArticle(heroArticle)}
            className="group relative overflow-hidden rounded-2xl border border-border/80 bg-surface/90 shadow-lg hover:border-primary/60 cursor-pointer transition-all duration-300"
          >
            {/* Top Category Tag */}
            <div className="px-5 pt-3 pb-2 text-[10px] font-black uppercase tracking-wider text-muted-foreground flex items-center justify-between border-b border-border/40 bg-surface-2/40">
              <span className="text-emerald-400 font-bold">{heroArticle.category}</span>
              <span>{heroArticle.timeAgo}</span>
            </div>

            {/* Wide 16:9 Image Container */}
            <div className="relative h-48 sm:h-64 w-full overflow-hidden bg-surface-2">
              <img
                src={heroArticle.image || heroCricket}
                alt={heroArticle.title}
                className="h-full w-full object-cover object-center group-hover:scale-105 transition-transform duration-500"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/30 to-transparent" />
              <div className="absolute top-3 left-3 bg-red-600 text-white text-[10px] font-black px-2.5 py-0.5 rounded-full shadow-md flex items-center gap-1">
                <Sparkles className="h-3 w-3" /> FEATURED STORY
              </div>
            </div>

            {/* Story Content Below Image */}
            <div className="p-5">
              <h2 className="font-display text-lg sm:text-xl font-black text-foreground group-hover:text-primary transition-colors leading-snug">
                {heroArticle.title}
              </h2>
              <p className="mt-2 text-xs text-muted-foreground leading-relaxed line-clamp-2">
                {heroArticle.summary}
              </p>
              <div className="mt-3 flex items-center justify-between text-[11px] font-semibold text-primary pt-2 border-t border-border/40">
                <span>Read Full Story &rarr;</span>
                <span className="text-muted-foreground">{heroArticle.author}</span>
              </div>
            </div>
          </div>

          {/* Tournament Category Filters (ALL / INTERNATIONAL / DOMESTIC) */}
          <div ref={fixturesSectionRef} className="scroll-mt-24 space-y-4">
            <div className="flex items-center gap-2 overflow-x-auto pb-1 scrollbar-none">
              <button
                type="button"
                onClick={() => setCategory("ALL")}
                className={cn(
                  "shrink-0 flex items-center gap-1.5 rounded-full px-4 py-1.5 text-xs font-bold transition-all border",
                  category === "ALL"
                    ? "bg-primary text-primary-foreground border-primary shadow-sm shadow-primary/20"
                    : "bg-surface text-muted-foreground border-border hover:bg-surface-2 hover:text-foreground"
                )}
              >
                <Globe2 className="h-3.5 w-3.5" /> All Fixtures
              </button>
              <button
                type="button"
                onClick={() => setCategory("INTERNATIONAL")}
                className={cn(
                  "shrink-0 flex items-center gap-1.5 rounded-full px-4 py-1.5 text-xs font-bold transition-all border",
                  category === "INTERNATIONAL"
                    ? "bg-primary text-primary-foreground border-primary shadow-sm shadow-primary/20"
                    : "bg-surface text-muted-foreground border-border hover:bg-surface-2 hover:text-foreground"
                )}
              >
                <span>🌍</span> International Series
              </button>
              <button
                type="button"
                onClick={() => setCategory("DOMESTIC")}
                className={cn(
                  "shrink-0 flex items-center gap-1.5 rounded-full px-4 py-1.5 text-xs font-bold transition-all border",
                  category === "DOMESTIC"
                    ? "bg-primary text-primary-foreground border-primary shadow-sm shadow-primary/20"
                    : "bg-surface text-muted-foreground border-border hover:bg-surface-2 hover:text-foreground"
                )}
              >
                <span>🏆</span> Domestic & T20 Leagues
              </button>
            </div>

            {/* Status Tabs: LIVE / UPCOMING / COMPLETED */}
            <div className="flex items-center justify-between gap-4">
              <div className="flex items-center gap-1.5 rounded-xl border border-border bg-surface p-1">
                {[
                  { id: "Live" as const, label: "Live Matches", icon: Radio, pulse: true },
                  { id: "Upcoming" as const, label: "Upcoming", icon: Clock },
                  { id: "Completed" as const, label: "Completed", icon: CalendarDays },
                ].map((t) => {
                  const active = tab === t.id;
                  const Icon = t.icon;
                  return (
                    <button
                      key={t.id}
                      type="button"
                      onClick={() => setTab(t.id)}
                      className={cn(
                        "flex items-center gap-2 rounded-lg px-3.5 py-1.5 text-xs font-bold transition-all",
                        active
                          ? "bg-primary text-primary-foreground shadow-sm"
                          : "text-muted-foreground hover:bg-surface-2 hover:text-foreground"
                      )}
                    >
                      {t.pulse && (
                        <span className="relative flex h-2 w-2">
                          <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-red-400 opacity-75" />
                          <span className="relative inline-flex h-2 w-2 rounded-full bg-red-500" />
                        </span>
                      )}
                      <Icon className="h-3.5 w-3.5" />
                      <span>{t.label}</span>
                    </button>
                  );
                })}
              </div>

              <button
                onClick={() => void load()}
                type="button"
                className="inline-flex items-center gap-1.5 rounded-lg border border-border bg-surface px-3 py-1.5 text-xs font-semibold text-muted-foreground hover:text-foreground transition-colors"
              >
                <RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin text-primary" : ""}`} /> Refresh
              </button>
            </div>

            {error && (
              <Card className="mb-4 border-destructive/30 bg-destructive/10">
                <p className="text-sm text-destructive">{error}</p>
              </Card>
            )}

            {/* Match Cards Feed */}
            <div className="space-y-4">
              {loading && <LoadingState label="Loading cricket fixtures..." />}

              {!loading &&
                visibleItems.map((m) => {
                  const pd = (m.providerData || {}) as any;
                  const isLive = m.status === "LIVE";
                  const isCompleted = m.status === "COMPLETED";

                  const flagA = pd.teamAFlag || getTeamFlag(m.teamA);
                  const flagB = pd.teamBFlag || getTeamFlag(m.teamB);
                  const codeA = pd.teamACode || m.teamA.slice(0, 3).toUpperCase();
                  const codeB = pd.teamBCode || m.teamB.slice(0, 3).toUpperCase();
                  const tournament = pd.tournament || (pd.category === "DOMESTIC" ? "Indian Premier T20 League" : "ICC T20 Championship");

                  return (
                    <Card
                      key={m._id}
                      className="p-0 overflow-hidden border-border/80 hover:border-primary/60 transition-all duration-200 shadow-md hover:shadow-xl bg-surface/95"
                    >
                      {/* Card Header Strip */}
                      <div className="flex items-center justify-between border-b border-border/70 bg-surface-2/70 px-4 py-2 text-xs">
                        <div className="flex items-center gap-2 truncate">
                          <span className="font-bold text-foreground truncate max-w-[280px]">
                            {tournament}
                          </span>
                          {pd.format && (
                            <span className="rounded bg-surface px-1.5 py-0.5 text-[10px] font-black uppercase text-muted-foreground border border-border">
                              {pd.format}
                            </span>
                          )}
                        </div>

                        <div className="flex items-center gap-2 shrink-0">
                          <span className="text-[11px] text-muted-foreground flex items-center gap-1">
                            <MapPin className="h-3 w-3 text-primary" />
                            {m.venue?.split(",")[0] || "Stadium"}
                          </span>
                          {isLive ? (
                            <span className="inline-flex items-center gap-1.5 rounded-md bg-red-500/20 px-2 py-0.5 text-[10px] font-black text-red-400 border border-red-500/40">
                              <span className="h-1.5 w-1.5 rounded-full bg-red-500 animate-pulse" /> LIVE
                            </span>
                          ) : (
                            <StatusBadge status={m.status} />
                          )}
                        </div>
                      </div>

                      {/* Score & Teams Arena */}
                      <div className="p-4 sm:p-5">
                        <div className="flex items-center justify-between gap-3">
                          {/* Team A */}
                          <div className="flex items-center gap-3 flex-1 min-w-0">
                            <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-surface-2 text-2xl shadow-inner border border-border">
                              {flagA}
                            </div>
                            <div className="min-w-0">
                              <p className="font-display text-base font-black tracking-tight text-foreground truncate">
                                {codeA}
                              </p>
                              <p className="text-[11px] text-muted-foreground truncate">{m.teamA}</p>
                            </div>
                          </div>

                          {/* Center: Score or VS */}
                          <div className="text-center px-2 flex flex-col items-center shrink-0 min-w-[140px]">
                            {isLive ? (
                              <div className="space-y-0.5">
                                <p className="font-display text-xl font-black text-primary">
                                  {pd.currentScore || 162}/{pd.currentWickets || 3}
                                </p>
                                <p className="text-[11px] font-semibold text-muted-foreground">
                                  ({pd.currentOvers || "16.4"} ov) &bull; CRR: {pd.crr || "9.72"}
                                </p>
                              </div>
                            ) : isCompleted ? (
                              <div className="space-y-0.5">
                                <span className="rounded-full bg-surface-2 px-2 py-0.5 text-[10px] font-bold text-emerald-400 border border-border">
                                  MATCH ENDED
                                </span>
                                <p className="text-[11px] text-muted-foreground font-semibold mt-1">
                                  {pd.statusText || "Result finalized"}
                                </p>
                              </div>
                            ) : (
                              <div className="space-y-0.5">
                                <span className="rounded-full bg-surface-2 border border-border px-2.5 py-0.5 font-display text-xs font-black text-primary">
                                  VS
                                </span>
                                <p className="text-[11px] text-muted-foreground font-semibold mt-1">
                                  {new Date(m.startTime).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
                                </p>
                              </div>
                            )}
                          </div>

                          {/* Team B */}
                          <div className="flex items-center justify-end gap-3 flex-1 min-w-0 text-right">
                            <div className="min-w-0">
                              <p className="font-display text-base font-black tracking-tight text-foreground truncate">
                                {codeB}
                              </p>
                              <p className="text-[11px] text-muted-foreground truncate">{m.teamB}</p>
                            </div>
                            <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-surface-2 text-2xl shadow-inner border border-border">
                              {flagB}
                            </div>
                          </div>
                        </div>

                        {/* Situation Ticker */}
                        {isLive && pd.statusText && (
                          <div className="mt-3 rounded-lg border border-primary/20 bg-primary/5 px-3 py-1.5 text-center text-xs font-semibold text-primary">
                            {pd.statusText}
                          </div>
                        )}

                        {/* Recent Balls Strip */}
                        {isLive && Array.isArray(pd.recentBalls) && pd.recentBalls.length > 0 && (
                          <div className="mt-3 flex items-center justify-center gap-1.5 text-xs">
                            <span className="text-[10px] font-bold text-muted-foreground mr-1">RECENT:</span>
                            {pd.recentBalls.map((b: string, i: number) => {
                              const isW = b === "W";
                              const isBoundary = b === "4" || b === "6";
                              return (
                                <span
                                  key={i}
                                  className={cn(
                                    "flex h-6 w-6 items-center justify-center rounded-full text-[10px] font-black border",
                                    isW
                                      ? "bg-red-500/20 text-red-400 border-red-500/50"
                                      : isBoundary
                                      ? "bg-emerald-500/20 text-emerald-400 border-emerald-500/50"
                                      : "bg-surface-2 text-foreground border-border"
                                  )}
                                >
                                  {b}
                                </span>
                              );
                            })}
                          </div>
                        )}
                      </div>

                      {/* Bottom Strip & Action Buttons */}
                      <div className="flex flex-col sm:flex-row items-center justify-between border-t border-border/80 bg-surface-2/40 px-4 py-3 gap-3">
                        <div className="flex items-center gap-2 text-xs">
                          <Trophy className="h-4 w-4 text-yellow-400" />
                          <span className="font-bold text-foreground">₹50,000 Mega Jackpot</span>
                          <span className="rounded bg-primary/20 px-1.5 py-0.2 text-[10px] font-black text-primary">
                            FREE ENTRY
                          </span>
                        </div>

                        <div className="flex items-center gap-2 w-full sm:w-auto">
                          <Button
                            asChild
                            variant="outlineGreen"
                            size="sm"
                            className="flex-1 sm:flex-initial font-bold text-xs gap-1.5"
                            onClick={() => select(m._id)}
                          >
                            <Link to="/live-match">
                              <Radio className="h-3.5 w-3.5 text-red-400" />
                              {isLive ? "LIVE CENTER" : "SCORECARD"}
                            </Link>
                          </Button>

                          <Button
                            asChild
                            variant="hero"
                            size="sm"
                            className="flex-1 sm:flex-initial font-bold text-xs gap-1.5"
                            onClick={() => select(m._id)}
                          >
                            <Link to="/contests">
                              JOIN CONTEST <ChevronRight className="h-3.5 w-3.5" />
                            </Link>
                          </Button>
                        </div>
                      </div>
                    </Card>
                  );
                })}

              {!loading && !filteredItems.length && (
                <EmptyState label={`No ${category.toLowerCase()} ${tab.toLowerCase()} matches found.`} />
              )}
              {!loading && hasMore && <LoadMoreButton onClick={loadMore} />}
            </div>
          </div>
        </div>

        {/* ========================================================= */}
        {/* RIGHT COLUMN (FEATURED VIDEOS) - 3 cols                    */}
        {/* ========================================================= */}
        <div className="lg:col-span-3 space-y-4">
          <div className="flex items-center justify-between border-b border-border/80 pb-2">
            <h3 className="text-red-500 font-display text-xs font-black uppercase tracking-wider flex items-center gap-1.5">
              <Video className="h-4 w-4 text-red-500" />
              <span>FEATURED VIDEOS</span>
            </h3>
            <span className="text-[10px] text-muted-foreground font-bold uppercase">HIGHLIGHTS</span>
          </div>

          <div className="space-y-4">
            {FEATURED_VIDEOS.map((v) => (
              <div
                key={v.id}
                onClick={() => setActiveVideo(v)}
                className="group cursor-pointer rounded-2xl overflow-hidden border border-border/70 bg-surface/70 hover:border-primary/60 transition-all p-2.5 shadow-sm"
              >
                <div className="relative h-36 rounded-xl overflow-hidden bg-surface-2 flex items-center justify-center mb-2.5">
                  <img
                    src={v.thumbnail}
                    alt={v.title}
                    className="h-full w-full object-cover group-hover:scale-105 transition-transform duration-300"
                  />
                  <div className="absolute inset-0 bg-black/40 group-hover:bg-black/20 transition-colors" />
                  <div className="bg-primary/90 text-primary-foreground rounded-full p-2.5 z-10 shadow-lg group-hover:scale-110 transition-transform">
                    <Play className="h-4 w-4 fill-current" />
                  </div>
                  <span className="absolute bottom-2 right-2 bg-black/80 text-white text-[10px] font-black px-1.5 py-0.5 rounded">
                    {v.duration}
                  </span>
                </div>
                <h4 className="text-xs font-bold text-foreground group-hover:text-primary transition-colors leading-snug line-clamp-2">
                  {v.title}
                </h4>
                <p className="text-[10px] text-muted-foreground mt-1">{v.views}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* ------------------------------------------------------------- */}
      {/* ARTICLE READING MODAL (Opens when clicking any news)           */}
      {/* ------------------------------------------------------------- */}
      {activeArticle && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in">
          <div className="relative w-full max-w-2xl max-h-[85vh] overflow-y-auto rounded-2xl border border-border bg-surface p-6 shadow-2xl space-y-4">
            <div className="flex items-center justify-between border-b border-border/60 pb-3">
              <span className="text-xs font-black uppercase text-primary tracking-wider">
                {activeArticle.category}
              </span>
              <button
                type="button"
                onClick={() => setActiveArticle(null)}
                aria-label="Close article modal"
                className="h-8 w-8 rounded-full bg-surface-2 hover:bg-surface text-muted-foreground hover:text-foreground flex items-center justify-center transition-colors"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <h2 className="font-display text-xl sm:text-2xl font-black text-foreground leading-tight">
              {activeArticle.title}
            </h2>

            <div className="flex items-center justify-between text-xs text-muted-foreground border-b border-border/40 pb-2">
              <span>{activeArticle.author || "Cricbuzz Staff"}</span>
              <span>{activeArticle.timeAgo}</span>
            </div>

            {activeArticle.image && (
              <div className="h-52 w-full overflow-hidden rounded-xl bg-surface-2">
                <img
                  src={activeArticle.image}
                  alt={activeArticle.title}
                  className="h-full w-full object-cover"
                />
              </div>
            )}

            <div className="space-y-3 text-sm text-foreground/90 leading-relaxed">
              {activeArticle.content.map((p, idx) => (
                <p key={idx}>{p}</p>
              ))}
            </div>

            <div className="pt-4 border-t border-border flex items-center justify-between">
              <span className="text-xs text-muted-foreground">Fantasy Cricket Arena &bull; Global Feed</span>
              <Button
                type="button"
                variant="hero"
                size="sm"
                onClick={() => setActiveArticle(null)}
              >
                Close Story
              </Button>
            </div>
          </div>
        </div>
      )}

      {/* ------------------------------------------------------------- */}
      {/* VIDEO PLAYER MODAL (Opens when clicking any video)            */}
      {/* ------------------------------------------------------------- */}
      {activeVideo && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-sm animate-in fade-in">
          <div className="relative w-full max-w-3xl rounded-2xl border border-border bg-surface p-6 shadow-2xl space-y-4">
            <div className="flex items-center justify-between border-b border-border/60 pb-3">
              <span className="text-xs font-black uppercase text-red-400 tracking-wider flex items-center gap-1.5">
                <Video className="h-4 w-4" /> CRICKET HIGHLIGHTS &bull; {activeVideo.duration}
              </span>
              <button
                type="button"
                onClick={() => setActiveVideo(null)}
                aria-label="Close video modal"
                className="h-8 w-8 rounded-full bg-surface-2 hover:bg-surface text-muted-foreground hover:text-foreground flex items-center justify-center transition-colors"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            {/* Video Player Display */}
            <div className="relative aspect-video w-full overflow-hidden rounded-xl bg-black flex items-center justify-center shadow-inner">
              <iframe
                title={activeVideo.title}
                className="w-full h-full"
                src={`https://www.youtube-nocookie.com/embed/${activeVideo.youtubeId}?autoplay=1&mute=0`}
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              />
            </div>

            <div>
              <h3 className="font-display text-lg font-bold text-foreground">{activeVideo.title}</h3>
              <p className="mt-1 text-xs text-muted-foreground leading-relaxed">{activeVideo.description}</p>
            </div>

            <div className="pt-3 border-t border-border flex items-center justify-between">
              <span className="text-xs text-muted-foreground">{activeVideo.views}</span>
              <Button
                type="button"
                variant="outlineGreen"
                size="sm"
                onClick={() => setActiveVideo(null)}
              >
                Close Player
              </Button>
            </div>
          </div>
        </div>
      )}
    </AppShell>
  );
}
